apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 11124githubjenkinsgo 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=11124githubjenkinsgo
    backstage.io/kubernetes-id: 11124githubjenkinsgo 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: 11124githubjenkinsgo
    quay.io/repository-slug: jsmid/rhtap-qe-jsmid
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 